In [2]:
!nvidia-smi

Sat Oct 25 14:01:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.57                 Driver Version: 581.57         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0             11W /   70W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

In [4]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
## Get tensor back as Python int
scalar.item()

7

In [7]:
## Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
## Matrix 
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [12]:
# Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [14]:
## Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2089, 0.3108, 0.2889, 0.0916],
        [0.1756, 0.1210, 0.6099, 0.4774],
        [0.7816, 0.7059, 0.0565, 0.5497]])

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.6099, 0.9171, 0.9095, 0.8453],
         [0.9581, 0.4201, 0.3956, 0.2284],
         [0.2043, 0.6541, 0.2391, 0.4187]],

        [[0.6651, 0.7285, 0.9519, 0.0339],
         [0.8066, 0.3802, 0.8535, 0.7208],
         [0.7140, 0.3779, 0.1305, 0.5847]]])

In [17]:
random_tensor.ndim

3

In [18]:
## Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) # height,width,colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
# Create a tensor of all zero
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zero*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
## Create a tensor of all ones 
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range of tensors and tensors-like

In [22]:
# use torch.arange()
one_to_ten=torch.arange(start=0,end=1000,step=80)
one_to_ten

tensor([  0,  80, 160, 240, 320, 400, 480, 560, 640, 720, 800, 880, 960])

In [23]:
#Create tensors like
ten_zeroes=torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensors
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,   ## What datatype is the tensor (e.g. float32,float16)
                             device="cpu", ## Switching to cpu or gpu(cuda) 
                             requires_grad=False)  ## Whether or not to track gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor,can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
##