## Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations.

In [1]:
## Create a tensor(default on the CPU)
import torch
tensor=torch.tensor([1,2,3],device="cpu")

## Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
## Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device="cuda")
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [10]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
## To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')