## Manipulating Tensors (tensor operations)

Tensor operation include:
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Matrix Multiplication

In [1]:
import torch
## Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [2]:
## Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [3]:
## Subtract 10
tensor-10

tensor([-9, -8, -7])

In [4]:
## Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix multiplication 

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [5]:
## Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [6]:
## Matrix multipliation
torch.matmul(tensor,tensor)

tensor(14)

In [7]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 4.2 ms


In [8]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 82.3 μs


tensor(14)

## One of the most common errors in deep learning

In [9]:
# Shapes for matrix multiplication
tensor_a=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_b=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
torch.mm(tensor_a,tensor_b)  #torch.mm is the same as torch.matmul (it's an alias for matrix multiplication)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [10]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [11]:
## To fix out tensor shape issues, we an manipulate the shape of one of our tensors using transpose
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [12]:
tensor_b.T.shape

torch.Size([2, 3])

In [13]:
torch.mm(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [16]:
## Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [17]:
## Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
## Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [20]:
## Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [21]:
## You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [22]:
## Get all values of 0th and 1st dimensions buut only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [23]:
## Get all vavlues of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [26]:
## Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [27]:
## Index on x to return 9
print(x[:,2,2])

## index on x to return 3,6,9
print(x[:,:,2])

tensor([9])
tensor([[3, 6, 9]])


## Pytorch tensors and numpy

Numpy is a popular scientific Python numerical computing Library
And because of this,Pytorch has funcionality to interact with it

In [ ]:
## Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) ##warning: when converting from numpy--> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise 
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [29]:
array.dtype

dtype('float64')

In [30]:
torch.arange(1.0,8.0).dtype

torch.float32

In [31]:
## Change the value of array, what will this do to 'tensor'?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [32]:
## Tensor to Numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to make random out of random)

In short how a neural network learns:

'start with random numbers --> tensor operations --> update random numbers to try and make them'
'better representations of the data --> again --> again -->again....'

To reduce the randomness in neural networks and PyTorch comes the concept of a 
*random seed*

In [33]:
torch.rand(3,3)

tensor([[0.1635, 0.5878, 0.3266],
        [0.2163, 0.0518, 0.2807],
        [0.4186, 0.2902, 0.1623]])

In [34]:
import torch
## Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0864, 0.2913, 0.6155, 0.1925],
        [0.8964, 0.2382, 0.4488, 0.1810],
        [0.5372, 0.9228, 0.4860, 0.9184]])
tensor([[0.9361, 0.1817, 0.5708, 0.6915],
        [0.4378, 0.9015, 0.0683, 0.2652],
        [0.5061, 0.1683, 0.4699, 0.6148]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
## Let's make some random but reproducible tensors
import torch

## Set the random seed
random_seed=42
torch.manual_seed(random_seed)

random_tensor_c=torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_d=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUS = faster computation on numbers thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything good

In [4]:
!nvidia-smi

Thu Oct 30 16:37:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.57                 Driver Version: 581.57         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P3             13W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with PyTorch

In [6]:
import torch
torch.cuda.is_available()

True

In [7]:
## setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
## Count number of devices 
torch.cuda.device_count()

1