## Manipulating Tensors (tensor operations)

Tensor operation include:
1.Addition
2.Subtraction
3.Multiplication
4.Division
5.Matrix Multiplication

In [ ]:
import torch
## Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [2]:
## Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [3]:
## Subtract 10
tensor-10

tensor([-9, -8, -7])

In [4]:
## Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix multiplication 

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [5]:
## Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [6]:
## Matrix multipliation
torch.matmul(tensor,tensor)

tensor(14)

In [7]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 10.4 ms


In [8]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 60.1 μs


tensor(14)

## One of the most common errors in deep learning

In [9]:
# Shapes for matrix multiplication
tensor_a=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_b=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
torch.mm(tensor_a,tensor_b)  #torch.mm is the same as torch.matmul (it's an alias for matrix multiplication)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [10]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [11]:
## To fix out tensor shape issues, we an manipulate the shape of one of our tensors using transpose
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [15]:
torch.mm(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])