## Reshaping,stacking,squeezing and unsqueezing tensors
1. Reshaping- reshapes an input tensor to a defined shape
2. View- Return a view of input tensor of certain shape but keep the same memory as the original tensor
3. Stacking- combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeeze - removes all '1' dimensions from a tensor
5. Unsqueeze - add a '1' dimension to a target tensor
6. Permute- Return a view of the input with dimensions permuted(swapped) in a certain way

In [1]:
## Let's create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
## Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [3]:
## Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
## Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [7]:
## Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [8]:
## torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [14]:
x_squeezed=x_reshaped.squeeze()

In [15]:
x_reshaped.squeeze().shape

torch.Size([9])

In [19]:
## torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [25]:
## torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3))
print(x_original.shape)

## Permute the original tensor to rearrange the axis (or dim) order
x_permute=torch.permute(x_original,(2,0,1))
x_permute.shape

torch.Size([224, 224, 3])


torch.Size([3, 224, 224])